spring:
  application:
    name: "accounts"

build:
  version: "1.0"

accounts:
  message: "Welcome to accounts microservice related production APIs "
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "{cipher}41da8d2f86f9f4cb0446f25b404ad04c97c0b60f25e93543789330916e60a9c948217f8ea6743d734caab72771504fda"
  onCallSupport:
    - 0xxxxxxxxx
