spring:
  application:
    name: "accounts"

build:
  version: "3.0"

accounts:
  message: "Welcome to accounts microservice related local APIs (modified)"
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "trankhanhduy18@gmail.com"
  onCallSupport:
    - 0xxxxxxxxx
